### PR TITLE
Update site-layout.md

### PR DESCRIPTION
**Pull request by melodykramer**
Added some more information to the top describing the site.

### CODE REVIEW

**Comment by melodykramer** [comment]
The hierarchy looks great. My one question is whether /help should also be associated with a /station. 

I believe Midas will eventually be skinned and adapted for each individual station. So the hierarchy for /help would be 

/help/WXXI/  - the main page for helping WXXI
/help/WXXI/tasks - the list of tasks that WXXI needs help with. See [Midas example](https://midas-dev.18f.us/tasks)
/help/WXXI/tasks/4 - the specific task that WXXI needs help with. See [Midas example](https://midas-dev.18f.us/tasks/8)
/help/WXXI/profile/30 - the people who have signed up to help WXXI with the tasks. See [Midas example](https://midas-dev.18f.us/profile/30)

**Comment by melodykramer** [comment]
One more comment: For the front page, I would also put /listen - I think this will be key in attracting visitors who are looking for audio.

**Comment by melodykramer** [comment]
My other comment would be "Do we want to call stations 'stations' or organizations?' Organizations would allow this to be adapted for other entities such as libraries etc.

**Comment by thequbit** [comment]
As for help, I think it should be organized like /station/{call}/help/tasks/{id}.  And /help would be a location to search for all possible topics.  Since we are 'station centric', I think the station should be the 'top' of the relational pyramid.

As for what shows up on the front-page: I was thinking this would be dynamic and would actually be set by the "administrators" of the site.  We can talk more about this once I get in to the code.

As for the organizations vs. stations, I agree 100%.

I'll update the doc and submit a PR against upstream.

**Pull request merged**
